apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: fetch-con-node-app
          image: strtwalker/pg-con-test:v1.0.3
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: "0.5" # Specify the CPU limit, e.g., 0.5 cores
              memory: "512Mi" # Specify the memory limit, e.g., 512 megabytes
            requests:
              cpu: "0.1" # Specify the CPU request, e.g., 0.1 cores
              memory: "256Mi" # Specify the memory request, e.g., 256 megabytes
          env:
          - name: DATABASE_HOST
            value: "postgres"  # the actual service-name
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_NAME
            value: "testdb"
          - name: DATABASE_USER
            value: "postgres"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials-secret
                key: postgres-password

---

apiVersion: v1
kind: Service
metadata:
  name: express-app-service
spec:
  selector:
    app: express-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
          - containerPort: 5432
          resources:
            limits:
              cpu: "1.5" 
              memory: "512Mi"
            requests:
              cpu: "1"
              memory: "256Mi"
          env:
          - name: POSTGRES_DB
            value: "testdb"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials-secret
                key: postgres-password

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials-secret
type: Opaque
data:
  postgres-password: cG9zdGdyZXM=  #postgres
