apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
          - containerPort: 5432
          resources:
            limits:
              cpu: "1.5" 
              memory: "512Mi"
            requests:
              cpu: "1"
              memory: "256Mi"
          env:
          - name: POSTGRES_DB
            value: "testdb"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials-secret
                key: postgres-password

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials-secret
type: Opaque
data:
  postgres-password: cG9zdGdyZXM=  #postgres